# Generated by Django 4.0.4 on 2022-05-09 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='customer_list',
            field=models.ManyToManyField(related_name='booked_rides', to=settings.AUTH_USER_MODEL),
        ),
    ]
